project_id = "bwdsswkrlomfwhwpkwww"

[functions.contact-submit]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
